package com.anime.antako.entities.db.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum Genre {
    ACCION("Acción"),
    AVENTURA("Aventura"),
    VANGUARDIA("Vanguardia"),
    PREMIADO("Premiado"),
    AMOR_ENTRE_CHICOS("Amor entre chicos"),
    COMEDIA("Comedia"),
    DRAMA("Drama"),
    FANTASIA("Fantasía"),
    AMOR_ENTRE_CHICAS("Amor entre chicas"),
    GASTRONOMIA("Gastronomía"),
    TERROR("Terror"),
    MISTERIO("Misterio"),
    ROMANCE("Romance"),
    CIENCIA_FICCION("Ciencia ficción"),
    RECUENTOS_DE_LA_VIDA("Recuentos de la vida"),
    DEPORTES("Deportes"),
    SOBRENATURAL("Sobrenatural"),
    SUSPENSO("Suspenso"),
    ECCHI("Ecchi"),
    EROTICO("Erótico"),
    HENTAI("Hentai"),
    ELENCO_ADULTO("Elenco adulto"),
    ANTROPOMORFICO("Antropomórfico"),
    CGDCT("CGDCT"),
    CUIDADO_DE_NINOS("Cuidado de niños"),
    DEPORTES_DE_COMBATE("Deportes de combate"),
    TRAVESTISMO("Travestismo"),
    DELINCUENTES("Delincuentes"),
    DETECTIVES("Detectives"),
    EDUCATIVO("Educativo"),
    HUMOR_ABSURDO("Humor absurdo"),
    GORE("Gore"),
    HAREM("Harem"),
    JUEGOS_DE_ALTO_RIESGO("Juegos de alto riesgo"),
    HISTORICO("Histórico"),
    IDOLS_FEMENINAS("Idols (femeninas)"),
    IDOLS_MASCULINOS("Idols (masculinos)"),
    ISEKAI("Isekai"),
    IYASHIKEI("Iyashikei"),
    POLIGONO_AMOROSO("Polígono amoroso"),
    CAMBIO_DE_SEXO_MAGICO("Cambio de sexo mágico"),
    CHICAS_MAGICAS("Chicas mágicas"),
    ARTES_MARCIALES("Artes marciales"),
    MECHA("Mecha"),
    MEDICO("Médico"),
    MILITAR("Militar"),
    MUSICA("Música"),
    MITOLOGIA("Mitología"),
    CRIMEN_ORGANIZADO("Crimen organizado"),
    CULTURA_OTAKU("Cultura otaku"),
    PARODIA("Parodia"),
    ARTES_ESCENICAS("Artes escénicas"),
    MASCOTAS("Mascotas"),
    PSICOLOGICO("Psicológico"),
    CARRERAS("Carreras"),
    REENCARNACION("Reencarnación"),
    REVERSE_HAREM("Reverse harem"),
    AMOR_ESTATICO("Amor estático"),
    SAMURAI("Samurái"),
    ESCOLAR("Escolar"),
    FARANDULA("Farándula"),
    ESPACIO("Espacio"),
    JUEGOS_DE_ESTRATEGIA("Juegos de estrategia"),
    SUPER_PODERES("Súper poderes"),
    SUPERVIVENCIA("Supervivencia"),
    DEPORTES_EN_EQUIPO("Deportes en equipo"),
    VIAJES_EN_EL_TIEMPO("Viajes en el tiempo"),
    VAMPIROS("Vampiros"),
    VIDEOJUEGOS("Videojuegos"),
    ARTES_VISUALES("Artes visuales"),
    LUGAR_DE_TRABAJO("Lugar de trabajo"),
    FANTASIA_URBANA("Fantasía urbana"),
    VILLANA("Villana"),
    JOSEI("Josei"),
    INFANTIL("Infantil"),
    SEINEN("Seinen"),
    SHOUJO("Shoujo"),
    SHOUNEN("Shounen");

    private final String value;
}

